const { Person, Transactions, Categories } = require('../models');
const seedCategories = require('./categorySeeds');
const sequelize = require('../config/connection');

sequelize.sync({ force: true }).then(async () => {
  seedCategories();
  await Person.create({
    username: 'abcd',
    password: 'password',
  });

  const userData = await Person.create({
    username: 'user1',
    password: 'password',
  });

  const transactionsData = [
    //food category
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 100,
      date: new Date(2024, 1, 1),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 120,
      date: new Date(2023, 1, 23),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 300,
      date: new Date(2023, 1, 14),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 90,
      date: new Date(2023, 2, 16),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 180,
      date: new Date(2023, 2, 26),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 30,
      date: new Date(2023, 3, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 430,
      date: new Date(2023, 3, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 310,
      date: new Date(2023, 4, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 130,
      date: new Date(2023, 4, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 230,
      date: new Date(2023, 5, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 190,
      date: new Date(2023, 5, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 100,
      date: new Date(2023, 6, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 130,
      date: new Date(2023, 6, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 350,
      date: new Date(2023, 7, 27),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 370,
      date: new Date(2023, 7, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 130,
      date: new Date(2023, 8, 22),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 170,
      date: new Date(2023, 8, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 200,
      date: new Date(2023, 9, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 170,
      date: new Date(2023, 9, 22),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 160,
      date: new Date(2023, 10, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 200,
      date: new Date(2023, 10, 18),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 230,
      date: new Date(2023, 11, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 220,
      date: new Date(2023, 11, 28),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 170,
      date: new Date(2024, 0, 22),
      categoryId: 1,
      personId: userData.id,
    },

    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 120,
      date: new Date(2023, 1, 23),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 300,
      date: new Date(2023, 1, 14),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 90,
      date: new Date(2023, 2, 16),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 180,
      date: new Date(2023, 2, 26),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 30,
      date: new Date(2023, 3, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 430,
      date: new Date(2023, 3, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 310,
      date: new Date(2023, 4, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 130,
      date: new Date(2023, 4, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 230,
      date: new Date(2023, 5, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 190,
      date: new Date(2023, 5, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 100,
      date: new Date(2023, 6, 20),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 130,
      date: new Date(2023, 6, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 350,
      date: new Date(2023, 7, 27),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 370,
      date: new Date(2023, 7, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 130,
      date: new Date(2023, 8, 22),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 170,
      date: new Date(2023, 8, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 200,
      date: new Date(2023, 9, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 170,
      date: new Date(2023, 9, 22),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 160,
      date: new Date(2023, 10, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 200,
      date: new Date(2023, 10, 18),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 230,
      date: new Date(2023, 11, 2),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 220,
      date: new Date(2023, 11, 28),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 170,
      date: new Date(2024, 0, 22),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 100,
      date: new Date(2024, 1, 1),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Walmart',
      description: 'Grocery',
      amount: 120,
      date: new Date(2024, 1, 7),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 150,
      date: new Date(2024, 1, 14),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Walmart',
      description: 'Grocery',
      amount: 200,
      date: new Date(2024, 1, 21),
      categoryId: 1,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Grocery',
      amount: 140,
      date: new Date(2024, 1, 23),
      categoryId: 1,
      personId: userData.id,
    },

    //Housing & Utilities
    {
      transactionType: 'Credit',
      name: 'Electricity',
      description: 'Bill',
      amount: 70,
      date: new Date(2024, 1, 23),
      categoryId: 2,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Electricity',
      description: 'Bill',
      amount: 80,
      date: new Date(2024, 0, 27),
      categoryId: 2,
      personId: userData.id,
    },

    //Entertainment
    {
      transactionType: 'Credit',
      name: 'Movies',
      description: 'AMC',
      amount: 40,
      date: new Date(2024, 1, 22),
      categoryId: 3,
      personId: userData.id,
    },

    //Gas
    {
      transactionType: 'Credit',
      name: `Sam's Club`,
      description: 'Gas',
      amount: 32,
      date: new Date(2024, 0, 20),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 45,
      date: new Date(2024, 0, 27),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 38,
      date: new Date(2024, 1, 7),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 47,
      date: new Date(2024, 1, 14),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 52,
      date: new Date(2024, 1, 23),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 32,
      date: new Date(2023, 1, 23),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 30,
      date: new Date(2023, 1, 14),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 65,
      date: new Date(2023, 2, 16),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 42,
      date: new Date(2023, 2, 26),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 37,
      date: new Date(2023, 3, 7),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 25,
      date: new Date(2023, 3, 20),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 31,
      date: new Date(2023, 4, 7),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 30,
      date: new Date(2023, 4, 20),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 28,
      date: new Date(2023, 5, 20),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 32,
      date: new Date(2023, 5, 2),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 28,
      date: new Date(2023, 6, 20),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 34,
      date: new Date(2023, 6, 2),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 35,
      date: new Date(2023, 7, 27),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 37,
      date: new Date(2023, 7, 7),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 28,
      date: new Date(2023, 8, 22),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 40,
      date: new Date(2023, 8, 2),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 26,
      date: new Date(2023, 9, 2),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 37,
      date: new Date(2023, 9, 22),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 16,
      date: new Date(2023, 10, 2),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 20,
      date: new Date(2023, 10, 18),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 23,
      date: new Date(2023, 11, 2),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 32,
      date: new Date(2023, 11, 28),
      categoryId: 4,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Holiday',
      description: 'Gas',
      amount: 27,
      date: new Date(2024, 0, 22),
      categoryId: 4,
      personId: userData.id,
    },

    //Travel
    {
      transactionType: 'Credit',
      name: 'Flight',
      description: 'Vacation',
      amount: 250,
      date: new Date(2024, 1, 22),
      categoryId: 5,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Hotel',
      description: 'Vacation',
      amount: 370,
      date: new Date(2024, 1, 22),
      categoryId: 5,
      personId: userData.id,
    },

    //Clothing
    {
      transactionType: 'Credit',
      name: 'MK',
      description: 'Jacket',
      amount: 270,
      date: new Date(2024, 1, 22),
      categoryId: 7,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'H&M',
      description: 'Dress',
      amount: 390,
      date: new Date(2024, 1, 20),
      categoryId: 7,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'H&M',
      description: 'T-shirt',
      amount: 140,
      date: new Date(2024, 0, 23),
      categoryId: 7,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'H&M',
      description: 'Jeans',
      amount: 230,
      date: new Date(2024, 1, 7),
      categoryId: 7,
      personId: userData.id,
    },

    // Other
    {
      transactionType: 'Credit',
      name: 'LA Fitness',
      description: 'Membership fee',
      amount: 85,
      date: new Date(2024, 1, 21),
      categoryId: 8,
      personId: userData.id,
    },
    {
      transactionType: 'Credit',
      name: 'Target',
      description: 'Active wear',
      amount: 165,
      date: new Date(2024, 1, 22),
      categoryId: 8,
      personId: userData.id,
    },
  ];

  await Transactions.bulkCreate(transactionsData, { validate: true });
  console.log('Tables Created');
});
